// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Jest         from "bs-jest/lib/es6/src/jest.js";
import * as Helpers$Nice from "../src/helpers.js";

describe("base62", (function () {
        Jest.test("should work with positive int", (function () {
                return Jest.Expect[/* toEqual */12]("1Z")(Jest.Expect[/* expect */0](Helpers$Nice.base62_of_int(123)));
              }));
        return Jest.test("should work with negative int", (function () {
                      return Jest.Expect[/* toEqual */12]("2Bi")(Jest.Expect[/* expect */0](Helpers$Nice.base62_of_int(-10000)));
                    }));
      }));

export {
  
}
/*  Not a pure module */
