// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Jest from "bs-jest/lib/es6/src/jest.js";

describe("Expect", (function () {
        return Jest.test("toBe", (function () {
                      return Jest.Expect[/* toBe */2](3)(Jest.Expect[/* expect */0](3));
                    }));
      }));

export {
  
}
/*  Not a pure module */
