// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Jest  from "bs-jest/lib/es6/src/jest.js";
import * as Nice  from "../src/nice.js";
import * as Block from "bs-platform/lib/es6/block.js";

describe("Nice", (function () {
        return Jest.test("toBe", (function () {
                      var cls = Nice.css(/* :: */[
                            /* Display */Block.__(0, [/* Flex */5]),
                            /* [] */0
                          ]);
                      Jest.Expect[/* toMatchSnapshot */16](Jest.Expect[/* expect */0](Nice.rule_cache));
                      return Jest.Expect[/* toMatchSnapshot */16](Jest.Expect[/* expect */0](cls));
                    }));
      }));

export {
  
}
/*  Not a pure module */
