// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Jest  from "bs-jest/lib/es6/src/jest.js";
import * as Nice  from "../src/nice.js";
import * as Block from "bs-platform/lib/es6/block.js";

describe("Vendor prefixes", (function () {
        Jest.test("prefixes display: flex", (function () {
                return Jest.Expect[/* toBe */2]("display:-webkit-flex;display:flex")(Jest.Expect[/* expect */0](Nice.string_of_style(/* Display */Block.__(0, [/* Flex */1]))));
              }));
        Jest.test("prefixes flex-direction: row", (function () {
                return Jest.Expect[/* toBe */2]("flex-direction:row;-webkit-flex-direction:row;-ms-flex-direction:row;-webkit-box-orient:horizontal;-webkit-box-direction:normal")(Jest.Expect[/* expect */0](Nice.string_of_style(/* FlexDirection */Block.__(31, [/* Row */0]))));
              }));
        Jest.test("prefixes flex-direction: column-reverse", (function () {
                return Jest.Expect[/* toBe */2]("flex-direction:column-reverse;-webkit-flex-direction:column-reverse;-ms-flex-direction:column-reverse;-webkit-box-orient:vertical;-webkit-box-direction:reverse")(Jest.Expect[/* expect */0](Nice.string_of_style(/* FlexDirection */Block.__(31, [/* ColumnReverse */3]))));
              }));
        return Jest.test("does not prefix display: block", (function () {
                      return Jest.Expect[/* toBe */2]("display:block")(Jest.Expect[/* expect */0](Nice.string_of_style(/* Display */Block.__(0, [/* Block */2]))));
                    }));
      }));

export {
  
}
/*  Not a pure module */
