// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest         = require("bs-jest/lib/js/src/jest.js");
var Helpers$Nice = require("../src/helpers.js");

describe("base62", (function () {
        Jest.test("should work with positive int", (function () {
                return Jest.Expect[/* toEqual */12]("1Z")(Jest.Expect[/* expect */0](Helpers$Nice.base62_of_int(123)));
              }));
        return Jest.test("should work with negative int", (function () {
                      return Jest.Expect[/* toEqual */12]("2Bi")(Jest.Expect[/* expect */0](Helpers$Nice.base62_of_int(-10000)));
                    }));
      }));

/*  Not a pure module */
