// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest  = require("bs-jest/lib/js/src/jest.js");
var Nice  = require("../src/nice.js");
var Block = require("bs-platform/lib/js/block.js");

describe("Nice", (function () {
        return Jest.test("toBe", (function () {
                      var cls = Nice.css(/* :: */[
                            /* Display */Block.__(0, [/* Flex */5]),
                            /* [] */0
                          ]);
                      Jest.Expect[/* toMatchSnapshot */16](Jest.Expect[/* expect */0](Nice.rule_cache));
                      return Jest.Expect[/* toMatchSnapshot */16](Jest.Expect[/* expect */0](cls));
                    }));
      }));

/*  Not a pure module */
