// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Block     from "bs-platform/lib/es6/block.js";
import * as Nice$Nice from "./nice.js";

var className = Nice$Nice.css(/* :: */[
      /* Display */Block.__(0, [/* Flex */1]),
      /* :: */[
        /* JustifyContent */Block.__(33, [/* Center */2]),
        /* :: */[
          /* AlignItems */Block.__(34, [/* FlexStart */0]),
          /* :: */[
            /* ResizeMode */Block.__(80, [/* Cover */1]),
            /* [] */0
          ]
        ]
      ]
    ]);

console.log(className);

export {
  className ,
  
}
/* className Not a pure module */
