// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as List  from "bs-platform/lib/es6/list.js";
import * as Block from "bs-platform/lib/es6/block.js";

function flex(style) {
  if (style.tag) {
    return /* :: */[
            style,
            /* [] */0
          ];
  } else {
    var match = style[0];
    if (match !== 4) {
      if (match >= 5) {
        return List.map((function (x) {
                      return /* Raw */Block.__(86, [
                                "display",
                                x
                              ]);
                    }), /* :: */[
                    "-webkit-box",
                    /* :: */[
                      "-moz-box",
                      /* :: */[
                        "-ms-flexbox",
                        /* :: */[
                          "-webkit-flex",
                          /* :: */[
                            "flex",
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]);
      } else {
        return /* :: */[
                style,
                /* [] */0
              ];
      }
    } else {
      return List.map((function (x) {
                    return /* Raw */Block.__(86, [
                              "display",
                              x
                            ]);
                  }), /* :: */[
                  "-webkit-inline-box",
                  /* :: */[
                    "-moz-inline-box",
                    /* :: */[
                      "-ms-inline-flexbox",
                      /* :: */[
                        "-webkit-inline-flex",
                        /* :: */[
                          "inline-flex",
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]);
    }
  }
}

export {
  flex ,
  
}
/* No side effect */
