// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as List     from "bs-platform/lib/es6/list.js";
import * as $$String from "bs-platform/lib/es6/string.js";

function combine_pairs(keys, values) {
  return $$String.concat(";", List.map((function (k) {
                    return $$String.concat(";", List.map((function (v) {
                                      return k + (":" + v);
                                    }), values));
                  }), keys));
}

export {
  combine_pairs ,
  
}
/* No side effect */
