// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block     = require("bs-platform/lib/js/block.js");
var Nice$Nice = require("./nice.js");

var className = Nice$Nice.css(/* :: */[
      /* Display */Block.__(0, [/* Flex */4]),
      /* :: */[
        /* MediaQuery */Block.__(83, [
            "screen",
            /* :: */[
              /* Display */Block.__(0, [/* Block */1]),
              /* [] */0
            ]
          ]),
        /* :: */[
          /* Color */Block.__(63, [/* Red */119]),
          /* [] */0
        ]
      ]
    ]);

console.log(className);

exports.className = className;
/* className Not a pure module */
