// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block     = require("bs-platform/lib/js/block.js");
var Nice$Nice = require("./nice.js");

var className = Nice$Nice.css(/* :: */[
      /* Display */Block.__(0, [/* Flex */4]),
      /* :: */[
        /* Color */Block.__(63, [/* Red */119]),
        /* :: */[
          /* MediaQuery */Block.__(83, [
              "screen",
              /* :: */[
                /* Display */Block.__(0, [/* Block */1]),
                /* :: */[
                  /* Color */Block.__(63, [/* Green */54]),
                  /* :: */[
                    /* Select */Block.__(85, [
                        ":hover",
                        /* :: */[
                          /* Color */Block.__(63, [/* Orange */104]),
                          /* :: */[
                            /* FontWeight */Block.__(67, [/* Bold */1]),
                            /* :: */[
                              /* Overflow */Block.__(37, [/* Hidden */1]),
                              /* :: */[
                                /* Supports */Block.__(84, [
                                    "(display: flex)",
                                    /* :: */[
                                      /* Color */Block.__(63, [/* Blue */10]),
                                      /* [] */0
                                    ]
                                  ]),
                                /* :: */[
                                  /* Select */Block.__(85, [
                                      ":hover",
                                      /* :: */[
                                        /* Color */Block.__(63, [/* Red */119]),
                                        /* :: */[
                                          /* Display */Block.__(0, [/* Block */1]),
                                          /* :: */[
                                            /* Select */Block.__(85, [
                                                ".ie6 &",
                                                /* :: */[
                                                  /* Color */Block.__(63, [/* Blue */10]),
                                                  /* [] */0
                                                ]
                                              ]),
                                            /* [] */0
                                          ]
                                        ]
                                      ]
                                    ]),
                                  /* [] */0
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]),
                    /* [] */0
                  ]
                ]
              ]
            ]),
          /* [] */0
        ]
      ]
    ]);

console.log(className);

exports.className = className;
/* className Not a pure module */
