// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Char       = require("bs-platform/lib/js/char.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var chars = /* array */[
  /* "0" */48,
  /* "1" */49,
  /* "2" */50,
  /* "3" */51,
  /* "4" */52,
  /* "5" */53,
  /* "6" */54,
  /* "7" */55,
  /* "8" */56,
  /* "9" */57,
  /* "a" */97,
  /* "b" */98,
  /* "c" */99,
  /* "d" */100,
  /* "e" */101,
  /* "f" */102,
  /* "g" */103,
  /* "h" */104,
  /* "i" */105,
  /* "j" */106,
  /* "k" */107,
  /* "l" */108,
  /* "m" */109,
  /* "n" */110,
  /* "o" */111,
  /* "p" */112,
  /* "q" */113,
  /* "r" */114,
  /* "s" */115,
  /* "t" */116,
  /* "u" */117,
  /* "v" */118,
  /* "w" */119,
  /* "x" */120,
  /* "y" */121,
  /* "z" */122,
  /* "A" */65,
  /* "B" */66,
  /* "C" */67,
  /* "D" */68,
  /* "E" */69,
  /* "F" */70,
  /* "G" */71,
  /* "H" */72,
  /* "I" */73,
  /* "J" */74,
  /* "K" */75,
  /* "L" */76,
  /* "M" */77,
  /* "N" */78,
  /* "O" */79,
  /* "P" */80,
  /* "Q" */81,
  /* "R" */82,
  /* "S" */83,
  /* "T" */84,
  /* "U" */85,
  /* "V" */86,
  /* "W" */87,
  /* "X" */88,
  /* "Y" */89,
  /* "Z" */90
];

function base62_of_int(x) {
  var x$1 = Pervasives.abs(x);
  var conversion = "";
  while(x$1 >= 1) {
    var newX = Math.floor(x$1 / 62) | 0;
    conversion = Char.escaped(Caml_array.caml_array_get(chars, x$1 - Caml_int32.imul(62, newX) | 0)) + conversion;
    x$1 = newX;
  };
  return conversion;
}

exports.base62_of_int = base62_of_int;
/* No side effect */
