// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List     = require("bs-platform/lib/js/list.js");
var $$String = require("bs-platform/lib/js/string.js");

function combine_pairs(keys, values) {
  return $$String.concat(";", List.map((function (k) {
                    return $$String.concat(";", List.map((function (v) {
                                      return k + (":" + v);
                                    }), values));
                  }), keys));
}

exports.combine_pairs = combine_pairs;
/* No side effect */
